---
title: "Upworthy Research Archive A/B Testing"
format: html
editor: visual
output: index.html
---

## 1. Define the experiment and research question

[Upworthy](#0) was a digital media publisher (from January 2013 to April 2015) that routinely used randomized experiments to test different ways of presenting its articles.

For each experiment, users visiting the Upworthy website were randomly assigned to see one of several **packages**, where each package consisted of a headline and image combination. Upworthy recorded the number of users who were shown each package (`impressions`) and the number who selected it (`clicks`).

The primary outcome is the **click-through rate (CTR)**:

$$CTR = \frac{\text{clicks}}{\text{impressions}}$$

Unlike the other two applications that observed single experiment, this [dataset](https://osf.io/jd64p/files/3vqmp) contains thousands of separate experiments, and individual experiments may contain more than two treatment variants.

**Research question:**\
How much do alternative headline and image packages affect click-through rates across Upworthy's randomized experiments?

## 2. Identify the treatment and control groups

Begin by inspecting the data:

```{r, echo = FALSE, warning = FALSE}
library(tidyverse)
library(broom)

upworthy <- read.csv("clean-upworthy-archive.csv")
summary(upworthy)

```

## 3. Define the relevant experiment metrics

## 4. Explore and check the experimental data

## 5. Estimate and test the treatment effect

## 6. Interpret the results

## 7. Make a practical recommendation
